### ISSUE TITLE
Can't compile - 

### ISSUE THREAD

**Issue by simonecesano** [dnmfarrell/Geo-libpostal#1]
I am trying to install Geo::libpostal.

After installing libpostal as per instructions, make test results in

    Test Summary Report
    -------------------
    t/libpostal.t (Wstat: 9 Tests: 2 Failed: 0)
      Non-zero wait status: 9
      Parse errors: No plan found in TAP output
    Files=1, Tests=2,  7 wallclock secs ( 0.04 usr  0.01 sys +  1.89 cusr  2.79 csys =  4.73 CPU)
    Result: FAIL
    Failed 1/1 test programs. 0/2 subtests failed.
    make: *** [Makefile:1050: test_dynamic] Error 255

and running (after make)

   perl -Ilib t/libpostal.t 

results in

    Can't find 'boot_Geo__libpostal' symbol in /usr/local/lib/libpostal.so
     at t/libpostal.t line 8.
    Compilation failed in require at t/libpostal.t line 8.
    BEGIN failed--compilation aborted at t/libpostal.t line 8.
    Undefined subroutine &Geo::libpostal::_teardown called at lib/Geo/libpostal.pm line 51.
    END failed--call queue aborted at t/libpostal.t line 8.

this 8. is on a Digital Ocean 2Gb instance - ``uname -a`` output

    Linux ubuntu-something 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

What am I doing wrong? same process on another Ubuntu 20 machine (not Digital Ocean though) worked ok (which is why I am grateful for the library - thanks for your work)

**Comment by dnmfarrell** [comment]
Hey, my first guess would be that the API for libpostal has changed - what version of libpostal are you installing?

**Comment by simonecesano** [comment]
the one from https://github.com/openvenues/libpostal 

    git clone https://github.com/openvenues/libpostal

and on from there.

I also tried with a bunch of new Digital Ocean instances (16Gb, 8 CPUs) and it worked perfectly down to 4Gb, while with one wit 2GB memory it failed again. Is there a way to work around this?

**Comment by dnmfarrell** [comment]
Ok yeah libpostal changed some function and type names in their v1.0.0 release. This is fixed on master. I've tested it against libpostal v1.0.0 so suggest you use that (there is a newer -alpha release that I haven't tried it against). A new version of Geo::libpostal is headed to cpan.

One bug I found was libpostal's configure was not downloading the data into the datadir. I had to download and manually extract the three data files into the datadir (these are all on the [release page](https://github.com/openvenues/libpostal/releases/tag/v1.0.0)).

Thanks for reporting!

**Comment by simonecesano** [comment]
Sorry to bother - I tried this too (libpostal from git, Geo::libpostal also from git) and it fails with less than 4Gb memory (but it works very well above that). Datadir is ok, BTW. So probably not a Geo::libpostal issue. I have checked the Python version for comparison - it also gets killed. Love this library when I have enough memory - thanks.

**Comment by dnmfarrell** [comment]
That's good to know, thanks for reporting. 4GB, wow.
